DROP USER C##LABDATABASE CASCADE;
CREATE USER C##LABDATABASE IDENTIFIED BY "password123";
GRANT CREATE SESSION TO C##LABDATABASE;

-- DROP ALL THE CONSTRAINTS

ALTER TABLE C##LABDATABASE.book
    DROP CONSTRAINT fk_author_id;

ALTER TABLE C##LABDATABASE.instance
    DROP CONSTRAINT fk_book_isbn;

ALTER TABLE C##LABDATABASE.hold
    DROP CONSTRAINT fk_instance_id;

ALTER TABLE C##LABDATABASE.hold
    DROP CONSTRAINT fk_patron_id;

ALTER TABLE C##LABDATABASE.loan
    DROP CONSTRAINT fk_hold_id;

-- DROP ALL THE TABLES
DROP TABLE C##LABDATABASE.author;
DROP TABLE C##LABDATABASE.patron;
DROP TABLE C##LABDATABASE.book;
DROP TABLE C##LABDATABASE.instance;
DROP TABLE C##LABDATABASE.hold;
DROP TABLE C##LABDATABASE.loan;